apiVersion: v1
kind: configmap
metadata:
  namespace: default
  name: mydb-config
  labels:
    app: mydb
    app.kubernetes.io/name: mydb
  data:
    primary.cnf: |
      [mysqld]
      log-bin
    replica.cnf: |
      [mysqld]
      super-read-only
